const QUESTIONS = {
    computer9: {
        ch1: {
            objective: [
                "What does ASCII stand for?\n(a) American Standard Code for Information Interchange\n(b) Advanced Standard Code for Information Interchange\n(c) American Standard Communication for Information Interchange\n(d) Advanced Standard Communication for Information Interchange",
                "Which of the following numbers is a valid binary number?\n(a) 1101102\n(b) 11011\n(c) 110.11\n(d) 1101A",
                "How many bits are used in standard ASCII encoding?\n(a) 7 bits\n(b) 8 bits\n(c) 16 bits\n(d) 32 bits",
                "Which is a key advantage of Unicode over ASCII?\n(a) It uses fewer bits\n(b) Represents many languages\n(c) Backward compatible with binary\n(d) Specific to English",
                "How many bytes store a typical integer?\n(a) 1\n(b) 2\n(c) 4\n(d) 8",
                "Difference between signed and unsigned integers?\n(a) Unsigned can't be negative\n(b) Signed has larger range\n(c) Unsigned is floating-point\n(d) Signed only positive",
                "In single precision, bits for exponent?\n(a) 23\n(b) 8\n(c) 11\n(d) 52",
                "Approximate range for single-precision floating-point numbers?\n(a) 1.4 × 10⁻⁴⁵ to 3.4 × 10³⁸\n(b) 1.4 × 10⁻³²⁴ to 3.4 × 10³⁰⁸\n(c) 4.9 × 10⁻³² to 1.8 × 10³⁸\n(d) 4.9 × 10⁻³²⁴ to 1.8 × 10³⁰⁸",
                "Tiny dots that make up an image are called?\n(a) Pixels\n(b) Bits\n(c) Bytes\n(d) Nodes",
                "In RGB model, RGB stands for?\n(a) Red, Green, Blue\n(b) Red, Gray, Black\n(c) Right, Green, Blue\n(d) Red, Green, Brown"
            ],
            short: [
                "What is the purpose of ASCII encoding?",
                "Difference between ASCII and Unicode?",
                "How does Unicode handle characters from multiple languages?",
                "Range of unsigned 2-byte integer?",
                "How is a negative integer represented in binary?",
                "Benefit of using unsigned integers?",
                "Effect of bits on integer range?",
                "Why use whole numbers for non-negative quantities?",
                "Range calculation for single precision floating-point?",
                "Why understand floating-point limitations in scientific computing?"
            ],
            long: [
                "Explain Unicode encoding with examples from multiple languages and code points.",
                "Describe in detail how integers are stored in memory.",
                "Explain converting decimal integers to binary and vice versa, including negative numbers."
            ]
        },
        ch2: {
            objective: [
                "Which Boolean expression is OR?\n(a) A · B\n(b) A + B\n(c) A\n(d) A ⊕ B",
                "Dual of A · 0 = 0?\n(a) A + 1 = 1\n(b) A + 0 = A\n(c) A · 1 = A\n(d) A · 0 = 0",
                "Logic gate true only if both inputs true?\n(a) OR\n(b) AND\n(c) XOR\n(d) NOT",
                "Half-adder carry generated by?\n(a) XOR\n(b) AND\n(c) OR\n(d) NOT",
                "Decimal equivalent of binary 1101?\n(a) 11\n(b) 12\n(c) 13\n(d) 14"
            ],
            short: [
                "Define a Boolean function with example.",
                "Significance of truth table in digital logic?",
                "Difference between analog and digital signals?",
                "Function of NOT gate with truth table?",
                "Purpose of Karnaugh map in simplifying Boolean expressions?"
            ],
            long: [
                "Explain usage of Boolean functions in computers.",
                "Construct a truth table for a Boolean expression with example."
            ]
        },
        ch3: {
            objective: [
                "First step in troubleshooting?\n(a) Establish theory\n(b) Implement solution\n(c) Identify problem\n(d) Document findings",
                "Why is troubleshooting important?\n(a) Saves money\n(b) Prevents professional help\n(c) Ensures smooth operation\n(d) Allows updates",
                "Step involving theory about problem cause?\n(a) Test theory\n(b) Establish theory\n(c) Implement solution\n(d) Verify system",
                "Next step after implementing solution?\n(a) Document findings\n(b) Test theory\n(c) Verify system\n(d) Plan action",
                "Example of identifying a problem?\n(a) Test laptop battery\n(b) Plan replacement\n(c) Notice laptop off\n(d) Write replacement note",
                "Importance of documenting findings?\n(a) Solve faster\n(b) Record reference\n(c) Efficient testing\n(d) Ensure solution",
                "Purpose of plan of action?\n(a) Identify problem\n(b) Verify system\n(c) Determine cause\n(d) Decide steps",
                "Why is troubleshooting important?\n(a) Keep hardware updated\n(b) Prevent software help\n(c) Ensure smooth systems\n(d) No updates needed",
                "Troubleshooting prevents?\n(a) Need professional help\n(b) Software updates\n(c) Downtime\n(d) Regular maintenance",
                "Example ensuring data integrity?\n(a) Identify software bug\n(b) Replace printer\n(c) Cooling pad\n(d) Update OS"
            ],
            short: [
                "First step in troubleshooting and its importance?",
                "Next step after identifying a problem?",
                "Importance of testing a theory? Example?",
                "Explain 'Implement the Solution' step.",
                "Why verify system after solution?"
            ],
            long: [
                "Discuss importance of troubleshooting in smooth system operation.",
                "Explain systematic process of troubleshooting step by step.",
                "Case study: printer not printing, identify problem and theory.",
                "Importance of documenting findings and actions.",
                "Analyze how troubleshooting ensures data integrity, prevents downtime, improves security.",
                "Describe software-related troubleshooting strategies.",
                "Recognize hardware failures (RAM, HDD).",
                "Importance of maintaining software and security.",
                "Methods for malware removal and OS updates.",
                "Compare different data backup methods."
            ]
        },
        ch4: {
            objective: [
                "Function of an operating system?\n(a) Compiling\n(b) Managing hardware\n(c) Printing only\n(d) Designing websites",
                "Which OS is open source?\n(a) Windows\n(b) Linux\n(c) macOS\n(d) MS-DOS",
                "Purpose of virtual memory?\n(a) Store files\n(b) Extend RAM\n(c) Increase processor speed\n(d) Protect system",
                "Which is NOT an OS?\n(a) Ubuntu\n(b) Windows 10\n(c) Microsoft Word\n(d) macOS",
                "What does file system do?\n(a) Manage devices\n(b) Organize/store files\n(c) Monitor network\n(d) Install software"
            ],
            short: [
                "Define an operating system and its purpose.",
                "Difference between single-user and multi-user OS?",
                "Role of process scheduler?",
                "Difference between RAM and virtual memory?",
                "How OS manages I/O devices?"
            ],
            long: [
                "Explain OS functions: memory, process, device management.",
                "Advantages/disadvantages of open-source vs proprietary OS.",
                "Describe computer booting process and OS role.",
                "Explain and compare file systems (FAT32, NTFS, ext4)."
            ]
        }
    }
};
